apiVersion: v1
kind: Service
metadata:
  name: springendava-service
  labels:
    app: springendava
spec:
  type: NodePort
  selector:
    app: springendava
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080